blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://github.com/E5presso/spakky-framework
    about: Check out the documentation before opening an issue
  - name: ðŸ’¬ Discussions
    url: https://github.com/E5presso/spakky-framework/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
